### PR TITLE
Site development

### PR DESCRIPTION
**Pull request by ccthecode**

### CODE REVIEW

**Comment by philtweir** [comment]
Thanks @ccthecode ! As suggested to @amurphy97 , I am keen to merge this even if there are some more changes, as we will be meeting people next week and it would be great to have a fresh look

**Comment by ccthecode** [comment]
You're welcome @philtweir 

I suggested to Andrea via mail some other points to consider before merging.


- [ ] I reckon that your contact form will be of utmost importance. Since you're expecting visitors. Right now it is setup under my  own account. Kindly follow the instructions in the README.md, so that you can have access to your form's data and get notified of all submissions.
- [ ] Finally, you might want to update your [terms-and-condition](https://github.com/flaxandteal/flaxandteal-website/blob/master/content/terms-and-condition/index.md) and [privacy-policy](https://github.com/flaxandteal/flaxandteal-website/blob/master/content/privacy-policy/index.md) page if that's important to you. Considering what is there is dummy content.

**Comment by philtweir** [comment]
Yes indeed, thank you for flagging! I think there are a number of changes that @amurphy97 has to feed back, but I think even as WIP this is better than what was in place so much appreciate your hard work @ccthecode

**Comment by ccthecode** [comment]
Got It! My pleasure @philtweir :)

**Pull request merged**
