### PR TITLE
Update stylesheet to ensure content fills the viewport

### PR DESCRIPTION
**Pull request by awflwafl**
## Description

A minor UI adjustment to remove whitespace around the coloured background of the website.

Before | After
--- | ---
image | image

## Technical Description

Adjusting the `body` `margin`. An adjustment to the footer's padding was also made to compensate for removed whitespace the text.

I found the duplicate copies of (seemingly) the same SCSS stylesheet in various directories somewhat confusing and made a change to the stylesheet that resulted in a change to the website.

### CODE REVIEW

**Comment by awflwafl** [comment]
Visited the Flax & Teal website and couldn't move past the seeing margins around the background image...

**Comment by philtweir** [comment]
LGTM, many thanks!

**Comment by awflwafl** [comment]
How's this redeployed? I'm not seeing the change appearing on the Flax & Teal website? Not sure if my mistake or not.

**Comment by philtweir** [comment]
Well spotted - hadn't run hugo on new code to regenerate docs folder -- done now :) (miss having a .gitlab-ci.yml)

**Pull request merged**
